version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./apps/backend
    env_file: ./apps/backend/.env
    ports:
      - "1337:1337"
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
    entrypoint: ["npm", "run"]
    command: develop

  web:
    build: ./apps/frontend
    env_file: ./apps/frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - api

volumes:
  postgres_data:

