services:
api:
build: ./apps/backend # requires a Dockerfile in apps/backend
env_file: ./apps/backend/.env
ports: ["8000:8000"]
volumes:
- ./apps/backend:/app
command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

web:
build: ./apps/frontend # requires a Dockerfile in apps/frontend
env_file: ./apps/frontend/.env.local
ports: ["3000:3000"]
volumes:
- ./apps/frontend:/app
depends_on:
- api